apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jbaxter1-tenant/partner-catalog/partner-catalog@sha256:e47dfc00536f839f249359a70dfc77515431fd7cf8ceb48629d632013a3a276d
        name: my-java-springboot
        resources: {}
status: {}
